name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  check-version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'requirements-dev.txt'
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Check version
      run: |
        [[ $(python setup.py --version) = ${GITHUB_REF/refs\/tags\/v/} ]] || exit 1
  
  build:
    strategy:
      matrix:
        os: [macos-13, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    
    needs: check-version

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'requirements-dev.txt'
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Build
      run: python setup.py bdist_blender_addon
    - name: Rename artifact
      shell: bash
      run: for filename in dist/*.zip; do mv "${filename}" "${filename%.zip}-${{ runner.os }}-${{ runner.arch }}.zip"; done;
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        fail_on_unmatched_files: true
        files: dist/*.zip

  build-manylinux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    
    needs: check-version
  
    steps:
    - uses: actions/checkout@v2
    - name: Select Python version
      run: echo "/opt/python/cp310-cp310/bin" >> $GITHUB_PATH
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Build
      run: python setup.py bdist_blender_addon
    - name: Rename artifact
      shell: bash
      run: for filename in dist/*.zip; do mv "${filename}" "${filename%.zip}-${{ runner.os }}.zip"; done;
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        fail_on_unmatched_files: true
        files: dist/*.zip
